### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by ghost** [GreenPix/dilia#6]
Hi there,

I was thinking. Can we use Travis or an other CI tool here?
You know, the _just in case_ scenario and everything :).

**Comment by Nemikolh** [comment]
Yes we can! :) 

The idea is to add to the project [karma](http://karma-runner.github.io/0.13/index.html) and [jasmine](https://jasmine.github.io/2.4/introduction.html) first. Then we add some tests and an appropriate `.travis.yml`.

I haven't look at how this should work with travis though, but [angular](https://github.com/angular/angular) is using it, so we can use their file as source of inspiration.
They also use something quite nice: [saucelabs](https://saucelabs.com/), it provides test for each browser kind, which is quite neat. :smiley: 

We might also consider having a [coveralls](https://coveralls.io/) badge as well. That would help to know quickly the coverage instead of looking for it in the travis output.

**Comment by lthms** [comment]
This was addressed by #13
